---
- name: "Practice from ansible"
  hosts: localhost
  become: true

  vars:
    secret_key_base: secret
    rails_env: production
    rails_log_to_stdout: 1
    db_host: 127.0.0.1
    db_port: 5432
    db_name: ruby
    db_user: ruby
    db_password: password

  pre_tasks:
  - name: "Disable Firewalld"
    ansible.builtin.service:
      name: "firewalld"
      state: "stopped"
      enabled: false

  - name: "Disable Selinux"
    ansible.posix.selinux:
      state: "disabled"
    register: selinux

  - name: "Disable Selinux (now)"
    ansible.builtin.shell:
      cmd: "setenforce 0"
    when: selinux.changed

  roles:
  - postgres
  - ruby
  - geerlingguy.nginx

  post_tasks:
  - name: "Configure nginx"
    ansible.builtin.template:
      src: "nginx.conf.j2"
      dest: "/etc/nginx/nginx.conf"
    register: nginx_conf

  - name: "Reload nginx"
    ansible.builtin.service:
      name: "nginx"
      state: "reloaded"
    when: nginx_conf.changed