---
- name: "Install Postgres"
  ansible.builtin.yum:
    name: "postgresql-server"
    state: "latest"

- name: "Check if DB is initialized"
  stat:
    path: "/var/lib/pgsql/data/PG_VERSION"
  register: pgdata_dir_version

- name: "initializing DB"
  command: postgresql-setup initdb
  when: not pgdata_dir_version.stat.exists
  become: true
  become_user: "postgres"
  become_method: sudo

- name: "Change authorization method"
  ansible.builtin.lineinfile:
    path: "/var/lib/pgsql/data/pg_hba.conf"
    regexp: "^host"
    line: "host    all             all             0.0.0.0/0               password"
    firstmatch: yes
    backup: true
  notify: "Restart postgres"

- name: "Change config postgresql.conf"
  ansible.builtin.lineinfile:
    path: "/var/lib/pgsql/data/postgresql.conf"
    regexp: "#listen_addresses = 'localhost'"
    line: "listen_addresses = '*'"
    firstmatch: yes
    backup: true
  notify: "Restart postgres"

- name: "Start service DB"
  ansible.builtin.service:
    name: "postgresql"
    state: "started"

- name: "Install psycopg2"
  ansible.builtin.yum:
    name: "python-psycopg2"
    state: "present"

- name: "Create DB"
  community.postgresql.postgresql_db:
    db: "{{ db_name }}"
  become: true
  become_user: "postgres"

- name: "Create DB_USER"
  community.postgresql.postgresql_user:
    db: "{{ db_name }}"
    user: "{{ db_user }}"
    password: "{{ db_password }}"
  become: true
  become_user: "postgres"

- name: "Restart Postgres with handlers"
  ansible.builtin.meta: flush_handlers