---
# - name: "Install Ruby"
#   community.general.snap:
#     name: "ruby"

# - name: "Install Bundler"
#   community.general.gem:
#     name: "bundler"

# - name: "Install Nokogiri"
#   community.general.gem:
#     name: "nokogiri"

- name: "Install libxml2"
  ansible.builtin.yum:
    name: "libxml2-devel"
    update_cache: yes
    state: "latest"

- name: "Copy files to /app"
  ansible.builtin.copy:
    src: "files/"
    dest: "/app"
    owner: "root"
    group: "root"
    mode: "0755"

- name: "Create ENV"
  ansible.builtin.template:
    src: "environment.j2"
    dest: "/app/environment"
    owner: root
    group: root
    mode: "0600"

- name: "Build from Gemfile"
  community.general.bundler:
    chdir: "/app"
    clean: true

  #bundle install --clean --no-cache --without development
    

- name: "Create ruby service"
  ansible.builtin.template:
    src: "ruby.service.j2"
    dest: "/etc/systemd/system/ruby.service"
    owner: "root"
    group: "root"
    mode: "0644"

- name: "Starting service"
  ansible.builtin.service:
    name: "ruby"
    state: "started"