---
- name: "Added new reposirories"
  ansible.builtin.yum:
    name: "{{ item }}"
    state: "latest"
  with_items:
    - centos-release-scl-rh
    - centos-release-scl

- name: "Install depence packages"
  ansible.builtin.yum:
    name: "{{ item }}"
    state: "present"
  with_items:
    - "@Development tools"
    - "libxml2-devel"
    - "libxslt-devel"
    - "libpqxx-devel"
    - "nodejs"

- name: "Install Ruby"
  ansible.builtin.yum:
    name: "{{ item }}"
    state: "present"
  with_items:
    - "rh-ruby26"
    - "rh-ruby26-ruby-devel"
    - "rh-ruby26-build"
    - "rh-ruby26-rubygem-bundler"

- name: "Create user for build project"
  ansible.builtin.user:
    name: "{{ ruby_user }}"

- name: "Copy project xPaste"
  ansible.builtin.copy:
    src: "files/xPaste"
    dest: "/opt"
    owner: "{{ ruby_user }}"
    group: "{{ ruby_user }}"
    mode: "0755"

- name: "Create ENV"
  ansible.builtin.template:
    src: "env.j2"
    dest: "/opt/xPaste/env"
    owner: "{{ ruby_user }}"
    group: "{{ ruby_user }}"
    mode: "0644"

- name: "Build from Gemfile"
  community.general.bundler:
    chdir: "/opt/xPaste"
    extra_args: "--path /opt/xPaste/.bundle"
  become: true
  become_user: "{{ ruby_user }}"
  environment:
    - PATH: "/opt/rh/rh-ruby26/root/usr/local/bin:/opt/rh/rh-ruby26/root/usr/bin:/usr/local/sbin:/sbin:/bin:/usr/sbin:/usr/bin"
    - LD_LIBRARY_PATH: "/opt/rh/rh-ruby26/root/usr/local/lib64:/opt/rh/rh-ruby26/root/usr/lib64"
    - PKG_CONFIG_PATH: "/opt/rh/rh-ruby26/root/usr/local/lib64/pkgconfig:/opt/rh/rh-ruby26/root/usr/lib64/pkgconfig"
    - XDG_DATA_DIRS: "/opt/rh/rh-ruby26/root/usr/local/share:/opt/rh/rh-ruby26/root/usr/share"

- name: "Create ruby service"
  ansible.builtin.template:
    src: "xpaste.service.j2"
    dest: "/etc/systemd/system/xpaste.service"
    owner: "root"
    group: "root"
    mode: "0644"

- name: "Starting service"
  ansible.builtin.service:
    name: "xpaste"
    state: "started"